version: '3'
services:
  qq_bot:
    image: syuchua01/my_qbot:latest
    container_name: my_qbot
    ports:
      - "3001:3001"
    volumes:
      - ./bot:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
<<<<<<< HEAD
=======

>>>>>>> 3f7974bfabac2b03626d31aaa896c1cf1c0a303f
